import {HomeIcon} from '@heroicons/react/24/solid';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

import About from '../components/about/About';
import ContactMe from '../components/contact-me/ContactMe';
import Header from '../components/header/Header';
import Hero from '../components/hero/Hero';
import Projects from '../components/projects/Projects';
import Skills from '../components/skills/Skills';
import WorkExperience from '../components/work-experience/WorkExperience';

export default function Home() {
  return (
    <div className="bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#F7AB0A]">
      <Head>
        <title>Niklaus Geisser Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/*BackgroundCircles*/}
      <section id="hero" className="snap-center">
        <Hero />
      </section>

      {/*Skills*/}
      <section id="section" className="snap-center">
        <About />
      </section>

      {/*Experiences*/}
      <section id="experience" className="snap-center">
        <WorkExperience />
      </section>

      {/*Skills*/}
      <section id="skills" className="snap-start">
        <Skills />
      </section>

      {/*Projects*/}
      <section id="projects" className="snap-start">
        <Projects />
      </section>

      {/*Contact Me*/}
      <section id="contact" className="snap-start">
        <ContactMe />
      </section>
      <Link href="#hero">
        <footer className="sticky bottom-5 w-full cursor-pointer">
          <div className="flex items-center justify-center">
            <HomeIcon className="text-gray-500 h-7 w-7" />
          </div>
        </footer>
      </Link>
    </div>
  );
}
