import Head from 'next/head';

import Header from '../components/header/Header';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Niklaus Geisser Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/*Hero*/}
      <section id="hero"></section>

      {/*About*/}

      {/*Experiences*/}

      {/*Skills*/}

      {/*Projects*/}

      {/*Contact Me*/}
    </div>
  );
}
